<h1 style='background-color:Powderblue'><center><font color='Green'>Naive Bayes Study in Mashroom Data Set</font></center></h1><br>

[Click here for detailed note about Mushrooms](https://sciencing.com/characteristics-mushrooms-8308611.html#:~:text=Physical%20Characteristics,can%20be%20occupied%20by%20pores.)<br>

# 1. <font color='Red'> Loading Essential library</font>

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.naive_bayes import GaussianNB, BernoulliNB,MultinomialNB
import warnings

# 2. <font color='Red'> Loading Data Set to python</font>

In [2]:
df=pd.read_csv(r'C:\Users\Lenovo\OneDrive\Desktop\ICT Academy\CS10 mushrooms.csv')

In [3]:
df.head(10)

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   
5     e         x           y         y       t    a               f   
6     e         b           s         w       t    a               f   
7     e         b           y         w       t    l               f   
8     p         x           y         w       t    p               f   
9     e         b           s         y       t    a               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   
5            c         b          n  ...                        s   
6            c         b          g  ...                        s   
7            c         b          n  ...                        s   
8            c         n          p  ...                        s   
9            c         b          g  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   
5                      w                      w         p          w   
6                      w                      w         p          w   
7                      w                      w         p          w   
8                      w                      w         p          w   
9                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  
5           o         p                 k          n       g  
6           o         p                 k          n       m  
7           o         p                 n          s       m  
8           o         p                 k          v       g  
9           o         p                 k          s       m  

[10 rows x 23 columns]

Here our data set is seems like contain only nominal values.

## Some Basic Preprocessing

### i. Shape of data set

In [5]:
print('The no of rows & coloumns are respectively',df.shape)

The no of rows & coloumns are respectively (8124, 23)


### ii. Checking Missing Values

In [6]:
df.isna().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

__Interpretation__
<p style='background-color:Red'>
Since the whole data where categorical variables, then the statistics about the sample data is meaningless.</p><br> 
Also  there is no missing values in data set so we can proceed with further steps.<br>

# 3. <font color='Red'> Feature Scaling </font>   

In [7]:
le=LabelEncoder()
df1=df.apply(le.fit_transform)
df1.head(5)

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [8]:
df1.isna().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [9]:
df1.corr()

class  cap-shape  cap-surface  cap-color  \
class                     1.000000   0.052951     0.178446  -0.031384   
cap-shape                 0.052951   1.000000    -0.050454  -0.048203   
cap-surface               0.178446  -0.050454     1.000000  -0.019402   
cap-color                -0.031384  -0.048203    -0.019402   1.000000   
bruises                  -0.501530  -0.035374     0.070228  -0.000764   
odor                     -0.093552  -0.021935     0.045233  -0.387121   
gill-attachment           0.129200   0.078865    -0.034180   0.041436   
gill-spacing             -0.348387   0.013196    -0.282306   0.144259   
gill-size                 0.540024   0.054050     0.208100  -0.169464   
gill-color               -0.530566  -0.006039    -0.161017   0.084659   
stalk-shape              -0.102019   0.063794    -0.014123  -0.456496   
stalk-root               -0.379361   0.030191    -0.126245   0.321274   
stalk-surface-above-ring -0.334593  -0.030417     0.089090  -0.060837   
stalk-surface-below-ring -0.298801  -0.032591     0.107965  -0.047710   
stalk-color-above-ring   -0.154003  -0.031659     0.066050   0.002364   
stalk-color-below-ring   -0.146730  -0.030390     0.068885   0.008057   
veil-type                      NaN        NaN          NaN        NaN   
veil-color                0.145142   0.072560    -0.016603   0.036130   
ring-number              -0.214366  -0.106534    -0.026147  -0.005822   
ring-type                -0.411771  -0.025457    -0.106407   0.162513   
spore-print-color         0.171961  -0.073416     0.230364  -0.293523   
population                0.298686   0.063413     0.021555  -0.144770   
habitat                   0.217179  -0.042221     0.163887   0.033925   

                           bruises      odor  gill-attachment  gill-spacing  \
class                    -0.501530 -0.093552         0.129200     -0.348387   
cap-shape                -0.035374 -0.021935         0.078865      0.013196   
cap-surface               0.070228  0.045233        -0.034180     -0.282306   
cap-color                -0.000764 -0.387121         0.041436      0.144259   
bruises                   1.000000 -0.061825         0.137359     -0.299473   
odor                     -0.061825  1.000000        -0.059590      0.063936   
gill-attachment           0.137359 -0.059590         1.000000      0.071489   
gill-spacing             -0.299473  0.063936         0.071489      1.000000   
gill-size                -0.369596  0.310495         0.108984     -0.108333   
gill-color                0.527120 -0.129213        -0.128567      0.100193   
stalk-shape               0.099364  0.459766         0.186485      0.080895   
stalk-root                0.244188 -0.205215         0.144063      0.350548   
stalk-surface-above-ring  0.460824  0.118617        -0.088916     -0.212359   
stalk-surface-below-ring  0.458983  0.061820        -0.116177     -0.213775   
stalk-color-above-ring    0.083538  0.174532         0.099299      0.274574   
stalk-color-below-ring    0.092874  0.169407         0.097160      0.253505   
veil-type                      NaN       NaN              NaN           NaN   
veil-color                0.119770 -0.057747         0.897518      0.073363   
ring-number               0.056788  0.111905         0.093236      0.243014   
ring-type                 0.692973 -0.281387        -0.146689     -0.195897   
spore-print-color        -0.285008  0.469055        -0.029524      0.047323   
population                0.088137 -0.043623         0.165575     -0.529253   
habitat                  -0.075095 -0.026610        -0.030304     -0.154680   

                          gill-size  gill-color  ...  \
class                      0.540024   -0.530566  ...   
cap-shape                  0.054050   -0.006039  ...   
cap-surface                0.208100   -0.161017  ...   
cap-color                 -0.169464    0.084659  ...   
bruises                   -0.369596    0.527120  ...   
odor                       0.310495   -0.12

**Conclusion**<br>
Here the correlation between the variables has not that much importance. since because the variables where categorical so it also meaning less <br>

# 4. <font color='Red'> Modeling  </font>   
## a. Splitting Data set into independent variable and Dependent variable.

In [10]:
X=df1.iloc[:,1:].values
y=df1.iloc[:,[0]].values
X

array([[5, 2, 4, ..., 2, 3, 5],
       [5, 2, 9, ..., 3, 2, 1],
       [0, 2, 8, ..., 3, 2, 3],
       ...,
       [2, 2, 4, ..., 0, 1, 2],
       [3, 3, 4, ..., 7, 4, 2],
       [5, 2, 4, ..., 4, 1, 2]])

**Note:**<br>
Here we took the whole variables except the "Class" column because the we can see that in given above link, which was the study about the Mushroom, in that it is clear that all preticulars of Head, Stem/Stalk and root has much influence in order to determine wheather it is edible or not.

## b. Scaling the Splitted Data set.

In [11]:
X=StandardScaler().fit_transform(X)
X

array([[ 1.02971224,  0.14012794, -0.19824983, ..., -0.67019486,
        -0.5143892 ,  2.03002809],
       [ 1.02971224,  0.14012794,  1.76587407, ..., -0.2504706 ,
        -1.31310821, -0.29572966],
       [-2.08704716,  0.14012794,  1.37304929, ..., -0.2504706 ,
        -1.31310821,  0.86714922],
       ...,
       [-0.8403434 ,  0.14012794, -0.19824983, ..., -1.50964337,
        -2.11182722,  0.28570978],
       [-0.21699152,  0.95327039, -0.19824983, ...,  1.42842641,
         0.28432981,  0.28570978],
       [ 1.02971224,  0.14012794, -0.19824983, ...,  0.16925365,
        -2.11182722,  0.28570978]])

## c. Further splitted the data set into Training set and Testing data.

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.3)
print('The no of rows and columns of training set of independent variables is:', X_train.shape)

The no of rows and columns of training set of independent variables is: (5686, 22)


## d. Fitting the different flavours of NB.
### <font color='tomato'>I Gaussing Naive Bayes </font>

In [15]:
fit1=GaussianNB().fit(X_train,y_train,)
y_pred_G=fit1.predict(X_test)
y_pred_G
warnings.filterwarnings('ignore')

In [29]:
c1=pd.DataFrame(y_test,y_pred_G)
c1.reset_index(inplace=True)
c1.rename(columns={'index':'Actual',0:'Predicted'},inplace=True)
c1.head()

Actual  Predicted
0       0          0
1       1          1
2       1          1
3       0          0
4       1          1

In [31]:
print('The Confusion Matrix of Gaussian Naive Bayes is :',confusion_matrix(y_test,y_pred_G))

The Confusion Matrix of Gaussian Naive Bayes is : [[1172   85]
 [  87 1094]]


Here we can see that among 2438, 2266 were correctly predicted and 172 wrongly predicted.

In [32]:
print('The Accuracy score of Gaussian Naive Bayes is :',accuracy_score(y_test,y_pred_G))

The Accuracy score of Gaussian Naive Bayes is : 0.9294503691550451


### <font color='tomato'>II Bernoulli Naive Bayes </font>

In [33]:
fit2=BernoulliNB().fit(X_train,y_train,)
y_pred_B=fit2.predict(X_test)
y_pred_B

array([0, 1, 1, ..., 1, 0, 0])

In [34]:
c2=pd.DataFrame(y_test,y_pred_B)
c2.reset_index(inplace=True)
c2.rename(columns={'index':'Actual',0:'Predicted'},inplace=True)
c2.head()

Actual  Predicted
0       0          0
1       1          1
2       1          1
3       0          0
4       1          1

In [35]:
print('The Confusion Matrix of Bernoulli Naive Bayes is :',confusion_matrix(y_test,y_pred_B))

The Confusion Matrix of Bernoulli Naive Bayes is : [[1228   29]
 [ 218  963]]


Here we can see that among 2438, 2191 were correctly predicted and 247 wrongly predicted.

In [36]:
print('The Accuracy score of Gaussian Naive Bayes is :',accuracy_score(y_test,y_pred_B))

The Accuracy score of Gaussian Naive Bayes is : 0.898687448728466


### <font color='tomato'>III Multinomial Naive Bayes </font><br>
<br>

__Introduction__<br>

Note that since in multinomial bayes naive there is disadvantage of negative values, so we use the values directly without and scalling on data.<br>


In [37]:
X1=df1.iloc[:,1:].values
y1=df1.iloc[:,[0]].values

In [38]:
X1_train,X1_test,y1_train,y1_test=train_test_split(X1,y1,random_state=12,test_size=0.3)

In [39]:
fit3=MultinomialNB().fit(X1_train,y1_train,)
y_pred_M=fit3.predict(X1_test)
y_pred_M

array([0, 0, 0, ..., 1, 0, 0])

In [40]:
c3=pd.DataFrame(y_test,y_pred_M)
c3.reset_index(inplace=True)
c3.rename(columns={'index':'Actual',0:'Predicted'},inplace=True)
c3.head()

Actual  Predicted
0       0          0
1       0          1
2       0          1
3       1          0
4       0          1

In [41]:
print('The Confusion Matrix of Multinomial Naive Bayes is :',confusion_matrix(y1_test,y_pred_M))

The Confusion Matrix of Multinomial Naive Bayes is : [[1152   93]
 [ 377  816]]


Like we saw in the above table,there may have more wrongful predictions occurs when we use the Multinomial Naive Bayes. Using the confusion matrix we can say that out 2438, the correctly predicted is 1968 and wrongly predicted is 470.

In [42]:
print('The Accuracy score of Multinomial Naive Bayes is :',accuracy_score(y1_test,y_pred_M))

The Accuracy score of Multinomial Naive Bayes is : 0.8072190319934373


**Conclusion**<br>
Since the accuracy score for Gaussian NB is greater than other two, we stick with Gaussian NB model.